<a href="https://colab.research.google.com/github/naserhusovic-droid/intro-to-eda-and-pandas/blob/main/04-exercise-eda-with-pandas/04-exercise-eda-with-pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<img src="https://github.com/naserhusovic-droid/intro-to-eda-and-pandas/blob/main/assets/ga-logo.png?raw=1" style="float: left; margin: 20px; height: 55px">

# Introduction to `pandas`

---

### About
`pandas` is the most popular python package for managing datasets and is used extensively by data scientists.

### Learning Objectives
- Explore the characteristics of a dataset at a high level with `pandas`.

### Notebook Guide
An exercise in practising:

- Reading data with `pandas`
- Exploring and manipulating data with `pandas`
    - Column operations
    - Filtering
    - Sorting
    - Writing data

# Scenario

You're an analyst working for CoolBricks - a new toy company who wants to compete with LEGO by producing their own bricks and sets. To better understand what kind of sets to create and at what price points, you are tasked with analyzing LEGO's catalogue over time.

The data comes from Kaggle: [https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time](https://www.kaggle.com/datasets/alexracape/lego-sets-and-prices-over-time)

We are going to use `pandas` to read and explore this data.

### Business question

What is the biggest set we could build (in terms of number of pieces) and what sort of price would we want to charge?

#### 1. Import `pandas` and read in the LEGO dataset

In [2]:
url = 'https://raw.githubusercontent.com/juanatga/intro-to-eda-and-pandas/main/data/lego.csv'

import pandas as pd

lego_df = pd.read_csv(url)

lego_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Set_ID            14936 non-null  object
 1   Name              14936 non-null  object
 2   Year              14936 non-null  int64
 3   Theme             14936 non-null  object
 4   Theme_Group       14915 non-null  object
 5   Subtheme          11495 non-null  object
 6   Category          14936 non-null  object
 7   Packaging         14936 non-null  object
 8   Num_Instructions  14936 non-null  int64
 9   Availability      14936 non-null  object
 10  Pieces            13133 non-null  float64
 11  Minifigures       7686 non-null   float64
 12  Owned             14771 non-null  float64
 13  Rating            14936 non-null  float64
 14  USD_MSRP          5837 non-null   float64
 15  Total_Quantity    12276 non-null  float64
 16  Current_Price     5442 non-null   float64
dtypes: float64(7), int64(2), object(8)
memory usage: 1.9+ MB

#### 2. So we can focus on just the columns that help answer the question, select only the following columns into a new `DataFrame` variable:

- name
- theme
- number of pieces
- retail price (USD_MSRP)

In [4]:
Naser = lego_df[["Name", "Theme", "Pieces", "USD_MSRP"]]

In [10]:
Naser.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      14936 non-null  object
 1   Theme     14936 non-null  object
 2   Pieces    13133 non-null  float64
 3   USD_MSRP  5837 non-null   float64
dtypes: float64(2), object(2)
memory usage: 466.9+ KB

#### 3. How many sets have a price greater than $100?

In [5]:
Naser["USD_MSRP"] > 100

0        False
1        False
2        False
3        False
4        False
         ...
14931    False
14932    False
14933    False
14934    False
14935    False
Name: USD_MSRP, Length: 14936, dtype: bool

In [6]:
Naser[Naser["USD_MSRP"] > 100]

                            Name          Theme  Pieces  USD_MSRP
4769     Imperial Star Destroyer      Star Wars  3096.0    269.99
5324            3-Seat Playtable           Gear     NaN    249.99
5973               Death Star II      Star Wars  3441.0    269.99
5974                 Sandcrawler      Star Wars  1669.0    139.99
6256          Cargo Train Deluxe           City   856.0    149.99
...                          ...            ...     ...       ...
14896  Temple of the Golden Idol  Indiana Jones  1545.0    149.99
14900  Monkie Kid's Team Hideout     Monkie Kid  1582.0    139.99
14901     Monkey King Ultra Mech     Monkie Kid  1705.0    159.99
14905  Dragon of the East Palace     Monkie Kid  2364.0    189.99
14907      Lunar New Year Parade       Seasonal  1653.0    129.99

[380 rows x 4 columns]

#### 4. What are the top 10 sets with the highest number of pieces?

In [7]:
Naser.sort_values(("Pieces"), ascending = False).head(10)

                                   Name           Theme   Pieces  USD_MSRP
13559                         World Map             Art  11695.0    249.99
13946                      Eiffel Tower           Icons  10001.0    629.99
13449                           Titanic           Icons   9090.0    679.99
12942                         Colosseum           Icons   9036.0    549.99
11928                 Millennium Falcon       Star Wars   7541.0    849.99
14380                   The Razor Crest       Star Wars   6187.0    599.99
14440  The Lord of the Rings: Rivendell           Icons   6167.0    499.99
14807              NINJAGO City Markets         Ninjago   6163.0    369.99
12369                   Hogwarts Castle    Harry Potter   6020.0    469.99
11437                         Taj Mahal  Creator Expert   5923.0    369.99

#### 5. Create a new column to measure "price per piece", which should be the price (USD_MSRP) divided by the number of pieces

In [11]:
Naser["Price"] = Naser["USD_MSRP"] / Naser["Pieces"]

/tmp/ipykernel_704/4144976046.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Naser["Price"] = Naser["USD_MSRP"] / Naser["Pieces"]

In [12]:
Naser.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14936 entries, 0 to 14935
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Name      14936 non-null  object
 1   Theme     14936 non-null  object
 2   Pieces    13133 non-null  float64
 3   USD_MSRP  5837 non-null   float64
 4   Price     5230 non-null   float64
dtypes: float64(3), object(2)
memory usage: 583.6+ KB

In [14]:
Naser["Price"] = Naser["USD_MSRP"] / Naser["Pieces"]
Naser

/tmp/ipykernel_704/4193923775.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  Naser["Price"] = Naser["USD_MSRP"] / Naser["Pieces"]

                          Name      Theme  Pieces  USD_MSRP  Price
0                PreSchool Set  PreSchool    16.0       NaN    NaN
1                PreSchool Set  PreSchool    20.0       NaN    NaN
2               Pre-School Set      Duplo    21.0       NaN    NaN
3                PreSchool Set  PreSchool    32.0       NaN    NaN
4                    Basic Set  Samsonite   330.0       NaN    NaN
...                        ...        ...     ...       ...    ...
14931        Creeper Key Chain       Gear     NaN      5.99    NaN
14932          Steve Key Chain       Gear     NaN      5.99    NaN
14933         Piglin Key Chain       Gear     NaN      5.99    NaN
14934   Fennec Shand Key Chain       Gear     NaN      5.99    NaN
14935  Scout Trooper Key Chain       Gear     NaN      5.99    NaN

[14936 rows x 5 columns]

#### 6. Use this column to find the top 10 most expensive sets by "price per piece"

In [15]:
Naser.sort_values(("Price"), ascending=False)[0:10]

,Name,Theme,Pieces,USD_MSRP,Price
13892,Character Pack Series 3 - Complete,Super Mario,0.0,4.99,inf
13806,LEGO Minifigures - Marvel Studios Series {Box ...,Collectable Minifigures,0.0,29.94,inf
14251,LEGO Minifigures - Series 22 {Box of 6 random ...,Collectable Minifigures,0.0,29.94,inf
9653,EV3 Intelligent Brick,Mindstorms,1.0,224.95,224.950
6342,NXT Intelligent Brick,Mindstorms,1.0,169.99,169.990
7695,Intelligent NXT Brick (Black),Mindstorms,1.0,169.99,169.990
13755,Small Hub,Education,2.0,214.95,107.475
9654,DC Rechargeable Battery,Education,1.0,99.95,99.950
8197,NXT DC Rechargeable Battery,Education,1.0,79.99,79.990
12927,Boost Hub,Powered Up,1.0,79.99,79.990

#### 7. Narrow the search to show the top 10 most expensive sets by "price per piece" for the "Icons" theme *only*

In [18]:
Naser[Naser["Theme"]=="Icons"].sort_values("Price", ascending=False).head(10)
condition = Naser["Theme"] == "Icons"
Naser[condition][0:10]

                             Name  Theme  Pieces  USD_MSRP     Price
12939               Haunted House  Icons  3231.0    299.99  0.092847
12940         Ghostbusters ECTO-1  Icons  2352.0    239.99  0.102037
12941              Elf Club House  Icons  1197.0     99.99  0.083534
12942                   Colosseum  Icons  9036.0    549.99  0.060867
12943        Crocodile Locomotive  Icons  1271.0     99.99  0.078670
13436              Police Station  Icons  2923.0    199.99  0.068419
13437    Volkswagen T2 Camper Van  Icons  2207.0    179.99  0.081554
13438              Flower Bouquet  Icons   756.0     59.99  0.079352
13439                 Bonsai Tree  Icons   878.0     49.99  0.056936
13440  Adidas Originals Superstar  Icons   731.0     79.99  0.109425

#### 8. What are the top 10 cheapest sets by "price per piece" in the "Icons" theme?

In [19]:
Naser[condition].tail(10)

                                   Name  Theme  Pieces  USD_MSRP     Price
14436                         Jazz Club  Icons  2899.0    229.99  0.079334
14437                Wildflower Bouquet  Icons   939.0     59.99  0.063887
14438          Dried Flower Centrepiece  Icons   812.0     49.99  0.061564
14439                               {?}  Icons     NaN       NaN       NaN
14440  The Lord of the Rings: Rivendell  Icons  6167.0    499.99  0.081075
14441    Land Rover Classic Defender 90  Icons  2336.0    239.99  0.102735
14539                 Blacktron Cruiser  Icons   356.0       NaN       NaN
14540           BIONICLE Tahu and Takua  Icons   219.0       NaN       NaN
14545                      Moving Truck  Icons   301.0       NaN       NaN
14576                         Daffodils  Icons   216.0     12.99  0.060139

#### 9. Export the `DataFrame` you created in question 2. to a new CSV file.

In [22]:
Naser.to_csv("Naser_2_csv", index=False)

### Reflection

What is your answer to the business question? Here it is as a reminder:

> What is the biggest set we could build (in terms of number of pieces) and what sort of price would we want to charge?

Reflect on your experience. How was working with `pandas` compared to other tools you already know?